version : 2.1
default: &default
  machine:
    image: circleci/classic:latest
commands:
  install_dotnet:
    steps:
      - run: wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
      - run: sudo dpkg -i packages-microsoft-prod.deb
      - run: sudo apt-get install apt-transport-https
      - run: sudo apt-get update
      - run: sudo apt-get install -y dpkg
      - run: sudo apt-get install dotnet-sdk-2.2
jobs:
  test:
    <<: *default
    steps:
      - checkout
      - install_dotnet
      - run: dotnet build src
      - run: cd src/tests && dotnet minicover instrument --workdir ../ --assemblies tests/**/bin/**/*.dll --sources lib/**/*.cs
      - run: cd src/tests && dotnet minicover reset
      - run: cd src/tests && for project in tests.csproj; do dotnet test $project --no-build; done
      - run: cd src/tests && dotnet minicover uninstrument --workdir ../
      - run: cd src/tests && dotnet minicover htmlreport --workdir ../
      - run: cd src/tests && dotnet minicover cloverreport --workdir ../
      - run: curl -s https://codecov.io/bash > ./src/codecov
      - run: chmod +x ./src/codecov
      - run: ./src/codecov -f "./src/clover.xml" -t $CODECOV_TOKEN
      - store_artifacts:
          path: src/coverage-html
          destination: coverage
  deploy:
    <<: *default
    steps:
      - checkout
      - install_dotnet
      - run: dotnet pack src/lib/lib.csproj -o publish
      - run: dotnet nuget push src/lib/publish/CronQuery.*.nupkg $NUGET_TOKEN
workflows:
  version: 2.1
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
