version : 2
defaults:
  machine:
    image: circleci/classic:latest
commands:
  install_dotnet:
    steps:
      - run: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
      - run: sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
      - run: sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
      - run: sudo apt-get update
      - run: sudo apt-get install dotnet-sdk-2.1
jobs:
  test:
    steps:
      - checkout
      - install_dotnet
      - run: dotnet build src
      - run: cd src/tests && dotnet minicover instrument --workdir ../ --assemblies tests/**/bin/**/*.dll --sources lib/**/*.cs
      - run: cd src/tests && dotnet minicover reset
      - run: cd src/tests && for project in tests.csproj; do dotnet test $project --no-build; done
      - run: cd src/tests && dotnet minicover uninstrument --workdir ../
      - run: cd src/tests && dotnet minicover cloverreport --workdir ../
      - run: curl -s https://codecov.io/bash > ./src/codecov
      - run: chmod +x ./src/codecov
      - run: ./src/codecov -f "./src/clover.xml" -t $CODECOV_TOKEN
  deploy:
    steps:
      - checkout
      - install_dotnet
      - run: dotnet pack src/lib/lib.csproj -o publish
      - reu: nuget push src/lib/publish/CronQuery.*.nupkg $NUGET_TOKEN
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
